/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;

/**
 *
 * @author nguye
 */
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import DTO.PhieuNhapDTO;
import BUS.PhieuNhapBUS;
import javax.swing.*;
import DTO.ChiTietPhieuNhapDTO;
import BUS.ChiTietPhieuNhapBUS;
import java.util.List;


import java.awt.Dimension;
public class ChiTietPhieuNhapDialog extends javax.swing.JDialog {
    private String maPhieuNhap;  
    /**
     * Creates new form ChiTietPhieuNhapDialog
     */
    public ChiTietPhieuNhapDialog(java.awt.Frame parent, boolean modal,String maPhieuNhap) {
        super(parent, modal);
        initComponents();
        this.maPhieuNhap=maPhieuNhap;
        hienThiBangPhieuNhap();
        hienThiThongTinPhieuNhap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_maphieunhap = new javax.swing.JTextField();
        text_nhanviennhap = new javax.swing.JTextField();
        text_nhacungcap = new javax.swing.JTextField();
        text_thoigiantao = new javax.swing.JTextField();
        table_phieunhap = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("THÔNG TIN PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel1)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        button1.setLabel("XUẤT FILE PDF");

        button2.setLabel("HỦY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("MÃ PHIẾU NHẬP");
        jPanel4.add(jLabel2);

        jLabel3.setText("NHÂN VIÊN NHẬP");
        jPanel4.add(jLabel3);

        jLabel4.setText("NHÀ CUNG CẤP");
        jPanel4.add(jLabel4);

        jLabel5.setText("THỜI GIAN TẠO");
        jPanel4.add(jLabel5);

        text_maphieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_maphieunhapActionPerformed(evt);
            }
        });
        jPanel4.add(text_maphieunhap);
        jPanel4.add(text_nhanviennhap);
        jPanel4.add(text_nhacungcap);
        jPanel4.add(text_thoigiantao);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout table_phieunhapLayout = new javax.swing.GroupLayout(table_phieunhap);
        table_phieunhap.setLayout(table_phieunhapLayout);
        table_phieunhapLayout.setHorizontalGroup(
            table_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        table_phieunhapLayout.setVerticalGroup(
            table_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jPanel3.add(table_phieunhap, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_maphieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_maphieunhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_maphieunhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            String maphieunhap="PN0222";
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChiTietPhieuNhapDialog dialog = new ChiTietPhieuNhapDialog(new javax.swing.JFrame(), true,maphieunhap);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void hienThiThongTinPhieuNhap(){
        // Lấy thông tin phiếu nhập từ BLL
        PhieuNhapDTO pn=new PhieuNhapDTO();
        PhieuNhapBUS pnbll=new PhieuNhapBUS();
         pn = pnbll.findphieunhapfrommapn(this.maPhieuNhap);

        // Hiển thị thông tin phiếu nhập lên các TextField
        if (pn != null) {
            text_maphieunhap.setText(pn.getMaPhieuNhap());
            text_thoigiantao.setText(pn.getNgayNhap().toString());
            text_nhacungcap.setText(pn.getMaNCC());
            text_nhanviennhap.setText(pn.getMaNhanVien());

        }

    }

public void hienThiBangPhieuNhap() {
    String[] columnNames = {"Mã quạt", "Số lượng", "Đơn giá", "Thành tiền"};

    // Lấy dữ liệu từ BLL
    List<ChiTietPhieuNhapDTO> dsCTPN = ChiTietPhieuNhapBUS.getChiTietPhieuNhapByMaPN(this.maPhieuNhap);

    // Chuyển sang Object[][]
    Object[][] data = new Object[dsCTPN.size()][4];
    for (int i = 0; i < dsCTPN.size(); i++) {
        ChiTietPhieuNhapDTO ct = dsCTPN.get(i);
        data[i][0] = ct.getMaQuat();
        data[i][1] = ct.getSoLuong();
        data[i][2] = ct.getDonGia();
        data[i][3] = ct.getThanhTien();
    }

    // Tạo model và bảng
    DefaultTableModel model = new DefaultTableModel(data, columnNames);
    JTable table = new JTable(model);

    // Cho bảng vào JScrollPane
    JScrollPane scrollPane = new JScrollPane(table);

    // Hiển thị vào panel
    table_phieunhap.removeAll();
    table_phieunhap.setLayout(new BorderLayout());
    table_phieunhap.add(scrollPane, BorderLayout.CENTER);
    table_phieunhap.revalidate();
    table_phieunhap.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel table_phieunhap;
    private javax.swing.JTextField text_maphieunhap;
    private javax.swing.JTextField text_nhacungcap;
    private javax.swing.JTextField text_nhanviennhap;
    private javax.swing.JTextField text_thoigiantao;
    // End of variables declaration//GEN-END:variables
}
