/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.*;
import BUS.QuatBUS;
import java.util.List;
import DTO.QuatDTO;
import BUS.NhaCungCapBUS;
import DTO.NhaCungCapDTO;
import BUS.PhieuNhapBUS;
import java.time.LocalDate;
import DTO.PhieuNhapDTO;
import DTO.ChiTietPhieuNhapDTO;
import BUS.ChiTietPhieuNhapBUS;
import BUS.QuatBUS;
import BUS.NhanVienBUS;
import BUS.NhaSanXuatBUS;
import com.kitfox.svg.A;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.JOptionPane;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;




/**
 *
 * @author nguye
 */
public class SuaPhieuNhapDialog extends javax.swing.JDialog {
    private String mapn;
    private DefaultTableModel modelPhieuNhap;  // Lưu model để thêm dòng sau này
    private JTable tablePhieuNhap;
    private DefaultTableModel modelsanpham; 
    private JTable tablesanpham;
    
    /**
     * Creates new form SuaPhieuNhapDialog
     */
    public SuaPhieuNhapDialog(java.awt.Frame parent, boolean modal,String mapn) {
        super(parent, modal);
        this.mapn=mapn;
        initComponents();
        loadComboBoxNhaCungCap();
        createSanPhamTable();
        createPhieuNhapTable();
        addsanphamtoform();
        lock_text();
        pack();                  
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_luu = new javax.swing.JButton();
        panel_tablephieunhap = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_tablesanpham = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_maquat = new javax.swing.JTextField();
        text_chatlieu = new javax.swing.JTextField();
        text_maphieunhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_tenquat = new javax.swing.JTextField();
        text_ngaysanxuat = new javax.swing.JTextField();
        text_nhanviennhap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_gianhap = new javax.swing.JTextField();
        text_nhasanxuat = new javax.swing.JTextField();
        combobox_nhacungcap = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_soluong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_addsanpham = new javax.swing.JButton();
        btn_suasoluong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("SỬA PHIẾU NHẬP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 399, 43, 372);
        jPanel1.add(jLabel16, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(974, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("TỔNG TIỀN : ");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setPreferredSize(new java.awt.Dimension(68, 20));
        jPanel6.add(jLabel15, java.awt.BorderLayout.CENTER);

        btn_luu.setText("LƯU THAY ĐỔI");
        btn_luu.setPreferredSize(new java.awt.Dimension(108, 30));
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });
        jPanel6.add(btn_luu, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout panel_tablephieunhapLayout = new javax.swing.GroupLayout(panel_tablephieunhap);
        panel_tablephieunhap.setLayout(panel_tablephieunhapLayout);
        panel_tablephieunhapLayout.setHorizontalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        panel_tablephieunhapLayout.setVerticalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(panel_tablephieunhap, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        panel_tablesanpham.setPreferredSize(new java.awt.Dimension(400, 488));

        javax.swing.GroupLayout panel_tablesanphamLayout = new javax.swing.GroupLayout(panel_tablesanpham);
        panel_tablesanpham.setLayout(panel_tablesanphamLayout);
        panel_tablesanphamLayout.setHorizontalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panel_tablesanphamLayout.setVerticalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        jPanel3.add(panel_tablesanpham, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(10, 3, 20, 10));

        jLabel3.setText("MÃ QUẠT");
        jPanel5.add(jLabel3);

        jLabel5.setText("CHẤT LIỆU");
        jPanel5.add(jLabel5);

        jLabel2.setText("MÃ PHIẾU NHẬP");
        jPanel5.add(jLabel2);
        jPanel5.add(text_maquat);
        jPanel5.add(text_chatlieu);
        jPanel5.add(text_maphieunhap);

        jLabel4.setText("TÊN QUẠT");
        jPanel5.add(jLabel4);

        jLabel1.setText("NGÀY SẢN XUẤT");
        jPanel5.add(jLabel1);

        jLabel6.setText("NHÂN VIÊN NHẬP");
        jPanel5.add(jLabel6);
        jPanel5.add(text_tenquat);
        jPanel5.add(text_ngaysanxuat);
        jPanel5.add(text_nhanviennhap);

        jLabel8.setText("GIÁ");
        jPanel5.add(jLabel8);

        jLabel9.setText("NHÀ SẢN XUẤT");
        jPanel5.add(jLabel9);

        jLabel7.setText("NHÀ CUNG CẤP");
        jPanel5.add(jLabel7);
        jPanel5.add(text_gianhap);
        jPanel5.add(text_nhasanxuat);

        combobox_nhacungcap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combobox_nhacungcap);

        jLabel10.setText("SỐ LƯỢNG");
        jPanel5.add(jLabel10);
        jPanel5.add(jLabel11);
        jPanel5.add(jLabel12);
        jPanel5.add(text_soluong);
        jPanel5.add(jLabel13);
        jPanel5.add(jLabel14);

        btn_addsanpham.setText("THÊM");
        jPanel5.add(btn_addsanpham);

        btn_suasoluong.setText("SỬA SỐ LƯỢNG");
        btn_suasoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suasoluongActionPerformed(evt);
            }
        });
        jPanel5.add(btn_suasoluong);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suasoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suasoluongActionPerformed
        // TODO add your handling code here:
        int row=tablePhieuNhap.getSelectedRow();
        if(row!=-1)
        {
            String soluong=modelPhieuNhap.getValueAt(row,3 ).toString();
           
            
        }
        String input = JOptionPane.showInputDialog(null, "Nhập số lượng mới:", "Cập nhật số lượng", JOptionPane.PLAIN_MESSAGE);

        if (input != null) { 
            try {
                int soLuongMoi = Integer.parseInt(input);
                System.out.println("Số lượng mới: " + soLuongMoi);
                if(soLuongMoi<0)
                {
                    JOptionPane.showMessageDialog(null, 
            "SỐ LƯỢNG PHẢI LỚN HƠN 0!", 
            "Thông báo", 
            JOptionPane.ERROR_MESSAGE);
                    return;
   
                }
       
                modelPhieuNhap.setValueAt(soLuongMoi, row, 3); 
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số nguyên hợp lệ!");
            }
        }

        
    }//GEN-LAST:event_btn_suasoluongActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
         ChiTietPhieuNhapBUS ctpnbus = new ChiTietPhieuNhapBUS();
         QuatBUS quatbus=new QuatBUS();
    boolean isUpdated=false ; 

    for (int i = 0; i < modelPhieuNhap.getRowCount(); i++) {
        String maQuat = modelPhieuNhap.getValueAt(i, 0).toString();
        String soluong = modelPhieuNhap.getValueAt(i, 3).toString();
        String dongia=modelPhieuNhap.getValueAt(i, 2).toString();
        
       
        int gia=Integer.parseInt(dongia);
        int sl = Integer.parseInt(soluong);  // Chuyển đổi số lượng thành kiểu int

        if(ctpnbus.checkexits(mapn, maQuat))
        {
            int soluongcu=ctpnbus.getChiTietPhieuNhapByMaQuat(mapn, maQuat).getSoLuong();
            System.out.println("so luong cu "+soluongcu+"so luong moi "+sl);
            boolean ctpnUpdated = ctpnbus.updatesoluong(mapn, sl, maQuat);
            boolean quatUpdated = quatbus.updatesoluongquat(maQuat, sl - soluongcu);
         if (ctpnUpdated && quatUpdated)
            {
                isUpdated=true;
            }
            else
            {
                isUpdated=false;
            }
            System.out.println("KHONG THEM CTPN");
        }
        else
        {
            System.out.println("THEM CTPN");
            ChiTietPhieuNhapDTO ctpndto=new ChiTietPhieuNhapDTO(this.mapn,maQuat,sl,gia    );
            if(ctpnbus.themChiTietPhieuNhap(ctpndto)&&quatbus.updatesoluongquat(maQuat, sl))
            {
                isUpdated=true;
            }
            else
            {
                isUpdated=false;
            }
            
        }
   

    }
        if (isUpdated) {
        JOptionPane.showMessageDialog(null, 
            "Cập nhật thành công!", 
            "Thông báo", 
            JOptionPane.INFORMATION_MESSAGE);
        dispose();
    } else {
        JOptionPane.showMessageDialog(null, 
            "Cập nhật thất bại!", 
            "Thông báo", 
            JOptionPane.ERROR_MESSAGE);
        dispose();
    }
        
    }//GEN-LAST:event_btn_luuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String mapn="test";
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaPhieuNhapDialog dialog = new SuaPhieuNhapDialog(new javax.swing.JFrame(), true,mapn);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void lock_text(){
        text_maquat.setEditable(false);
        text_chatlieu.setEditable(false);
        text_gianhap.setEditable(false);
        text_maphieunhap.setEditable(false);
        text_ngaysanxuat.setEditable(false);
        text_nhanviennhap.setEditable(false);
        text_nhasanxuat.setEditable(false);
        text_tenquat.setEditable(false);
        
        
    }
    
    private void createPhieuNhapTable() {
        String[] columnNames = {"Mã", "Tên", "Giá", "Số lượng", "Ngày sản xuất", "Chất liệu","Nhả Sản Xuất"};
        modelPhieuNhap = new DefaultTableModel(columnNames, 0); // Tạo model rỗng
        tablePhieuNhap = new JTable(modelPhieuNhap);
        JScrollPane scrollPane = new JScrollPane(tablePhieuNhap);
        scrollPane.setPreferredSize(new Dimension(800, 150));
        ChiTietPhieuNhapBUS ctpnbus=new ChiTietPhieuNhapBUS();
        QuatBUS quatbus= new QuatBUS();
        List<ChiTietPhieuNhapDTO>dsctpn=new ArrayList<>();
        dsctpn=ctpnbus.getChiTietPhieuNhapByMaPN(mapn);
        
        
    for (ChiTietPhieuNhapDTO ctpn : dsctpn) {
        Object[] rowData = {
            ctpn.getMaQuat(),
            quatbus.timTheoMaQuat(ctpn.getMaQuat()).getTenQuat(),
            ctpn.getDonGia(),
            ctpn.getSoLuong(),
            quatbus.timTheoMaQuat(ctpn.getMaQuat()).getNgaySanXuat(),
            quatbus.timTheoMaQuat(ctpn.getMaQuat()).getChatLieu(),
            quatbus.timTheoMaQuat(ctpn.getMaQuat()).getMaNSX()
        };
        modelPhieuNhap.addRow(rowData);
    }


        panel_tablephieunhap.setLayout(new BorderLayout());
        panel_tablephieunhap.removeAll();
        panel_tablephieunhap.add(scrollPane, BorderLayout.SOUTH);
        panel_tablephieunhap.revalidate();
        panel_tablephieunhap.repaint();
    }


    
    private void addsanphamtoform() {
    btn_addsanpham.addActionListener(e -> {
        String ma = text_maquat.getText();
        String ten = text_tenquat.getText();
        String chatlieu = text_chatlieu.getText();
        String ngaySX = text_ngaysanxuat.getText();
        String NhaSanXuat=text_nhasanxuat.getText();

       

        int gia = 0;
        int soLuong = 0;

        try {
            gia = Integer.parseInt(text_gianhap.getText());
            soLuong = Integer.parseInt(text_soluong.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Giá hoặc số lượng không hợp lệ");
            return;
        }

        modelPhieuNhap.addRow(new Object[]{ma, ten, gia, soLuong, ngaySX, chatlieu,NhaSanXuat});
    });
}

    
    
    
    
    
       private void loadComboBoxNhaCungCap() {
        NhaCungCapBUS nhaCungCapBLL = new NhaCungCapBUS();
        List<NhaCungCapDTO> danhSachNCC = nhaCungCapBLL.layTatCa();

        combobox_nhacungcap.removeAllItems(); 

        for (NhaCungCapDTO ncc : danhSachNCC) {
            combobox_nhacungcap.addItem(ncc.getTenNCC()); 
        }
        PhieuNhapBUS pnbus=new PhieuNhapBUS();
        NhaCungCapBUS nccbus=new NhaCungCapBUS();
        String mancc=pnbus.findphieunhapfrommapn(mapn).getMaNCC();
        String tenncc=nccbus.layTenNhaCungCapTheoMa(mancc);
        combobox_nhacungcap.setSelectedItem(tenncc);
        String fixedItem = combobox_nhacungcap.getSelectedItem().toString();

        combobox_nhacungcap.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                combobox_nhacungcap.setSelectedItem(fixedItem);
            }
        });


    }
       
       
       
    
    private void createSanPhamTable() {

        QuatBUS quatBLL = new QuatBUS();
        NhanVienBUS nhanvienbus=new NhanVienBUS();
        NhaSanXuatBUS nsxbus=new NhaSanXuatBUS();
        List<QuatDTO> danhSachQuat = quatBLL.layTatCa();

        String[] columnNames = {"Mã quạt", "Tên quạt", "Số lượng tồn"};
        Object[][] data = new Object[danhSachQuat.size()][3];

        for (int i = 0; i < danhSachQuat.size(); i++) {
            QuatDTO quat = danhSachQuat.get(i);
            data[i][0] = quat.getMaQuat();
            data[i][1] = quat.getTenQuat();
            data[i][2] = quat.getSoLuongTon();

        }

        modelsanpham = new DefaultTableModel(data, columnNames);
        tablesanpham = new JTable(modelsanpham);
        JScrollPane scrollPane = new JScrollPane(tablesanpham);

   
        tablesanpham.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tablesanpham.getSelectedRow();
                if (selectedRow >= 0) {
                    QuatDTO selectedQuat = danhSachQuat.get(selectedRow);
                    text_maquat.setText(selectedQuat.getMaQuat());
                    text_tenquat.setText(selectedQuat.getTenQuat());
                    text_chatlieu.setText(selectedQuat.getChatLieu());
                    text_ngaysanxuat.setText(selectedQuat.getNgaySanXuat());
                    String tennhasanxuat=nsxbus.getTenNXSByMaNSX(selectedQuat.getMaNSX());
                    System.out.println(tennhasanxuat);
                    text_nhasanxuat.setText(tennhasanxuat);

                  
                }
            }
        });
        
        panel_tablesanpham.setLayout(new java.awt.BorderLayout());
        panel_tablesanpham.removeAll();
        panel_tablesanpham.add(scrollPane, java.awt.BorderLayout.CENTER);
        panel_tablesanpham.revalidate();
        panel_tablesanpham.repaint();
     
        PhieuNhapBUS pnbll=new PhieuNhapBUS();
        text_maphieunhap.setText(this.mapn);
        text_nhanviennhap.setText(nhanvienbus.getNameNVByMaNV(pnbll.findphieunhapfrommapn(this.mapn).getMaNhanVien()));
        
         
    ;


    }


    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addsanpham;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_suasoluong;
    private javax.swing.JComboBox<String> combobox_nhacungcap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_tablephieunhap;
    private javax.swing.JPanel panel_tablesanpham;
    private javax.swing.JTextField text_chatlieu;
    private javax.swing.JTextField text_gianhap;
    private javax.swing.JTextField text_maphieunhap;
    private javax.swing.JTextField text_maquat;
    private javax.swing.JTextField text_ngaysanxuat;
    private javax.swing.JTextField text_nhanviennhap;
    private javax.swing.JTextField text_nhasanxuat;
    private javax.swing.JTextField text_soluong;
    private javax.swing.JTextField text_tenquat;
    // End of variables declaration//GEN-END:variables
}
