/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.*;
import BUS.QuatBUS;
import java.util.List;
import DTO.QuatDTO;
import BUS.NhaCungCapBUS;
import DTO.NhaCungCapDTO;
import BUS.PhieuNhapBUS;
import java.time.LocalDate;
import DTO.PhieuNhapDTO;
import DTO.ChiTietPhieuNhapDTO;
import BUS.ChiTietPhieuNhapBUS;
import BUS.QuatBUS;
import BUS.NhanVienBUS;
import BUS.NhaSanXuatBUS;
import javax.swing.UIManager;

/**
 *
 * @author nguye
 */

import GUI.LoginFrame;

public class ThemPhieuNhapDialog extends javax.swing.JDialog {
    public String manv;
    private DefaultTableModel modelPhieuNhap;  // Lưu model để thêm dòng sau này
    private JTable tablePhieuNhap;
    
    private DefaultTableModel modelsanpham; 
    private JTable tablesanpham;
    /**
     * Creates new form thempn
     */
    public ThemPhieuNhapDialog(java.awt.Frame parent, boolean modal,String manv) {
        super(parent, modal);
        this.manv=manv;
        initComponents();
        createSanPhamTable();
        createPhieuNhapTable();
        loadComboBoxNhaCungCap();
        addsanphamtoform();
        pack();                      // Tự động căn kích thước theo nội dung
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tittle = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        txt_tongtien = new javax.swing.JLabel();
        btn_nhaphang = new javax.swing.JButton();
        panel_tablephieunhap = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel = new java.awt.Panel();
        panel_tablesanpham = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_maquat = new javax.swing.JTextField();
        txt_chatlieu = new javax.swing.JTextField();
        txt_maphieunhap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tenquat = new javax.swing.JTextField();
        txt_ngaysanxuat = new javax.swing.JTextField();
        txt_tennhanvien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        txt_nhasanxuat = new javax.swing.JTextField();
        combobox_nhacungcap = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_addsanpham = new javax.swing.JButton();
        btn_editsanpham = new javax.swing.JButton();
        btn_deletesanpham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_tittle.setPreferredSize(new java.awt.Dimension(1077, 115));
        panel_tittle.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("THÊM PHIẾU NHẬP");
        panel_tittle.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(panel_tittle, java.awt.BorderLayout.PAGE_START);

        panel2.setPreferredSize(new java.awt.Dimension(933, 200));
        panel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        txt_tongtien.setText("TỔNG TIỀN :");
        txt_tongtien.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txt_tongtien.setPreferredSize(new java.awt.Dimension(65, 10));
        jPanel1.add(txt_tongtien, java.awt.BorderLayout.CENTER);

        btn_nhaphang.setText("NHẬP HÀNG");
        btn_nhaphang.setPreferredSize(new java.awt.Dimension(150, 35));
        btn_nhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhaphangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nhaphang, java.awt.BorderLayout.PAGE_END);

        panel2.add(jPanel1, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout panel_tablephieunhapLayout = new javax.swing.GroupLayout(panel_tablephieunhap);
        panel_tablephieunhap.setLayout(panel_tablephieunhapLayout);
        panel_tablephieunhapLayout.setHorizontalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        panel_tablephieunhapLayout.setVerticalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panel2.add(panel_tablephieunhap, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel2, java.awt.BorderLayout.PAGE_END);

        panel3.setLayout(new java.awt.BorderLayout());

        panel.setPreferredSize(new java.awt.Dimension(400, 454));
        panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panel_tablesanphamLayout = new javax.swing.GroupLayout(panel_tablesanpham);
        panel_tablesanpham.setLayout(panel_tablesanphamLayout);
        panel_tablesanphamLayout.setHorizontalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panel_tablesanphamLayout.setVerticalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        panel.add(panel_tablesanpham, java.awt.BorderLayout.CENTER);

        panel3.add(panel, java.awt.BorderLayout.WEST);

        panel5.setLayout(new java.awt.GridLayout(10, 3, 70, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("MÃ QUẠT");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setMaximumSize(new java.awt.Dimension(37, 10));
        jLabel7.setPreferredSize(new java.awt.Dimension(20, 10));
        panel5.add(jLabel7);

        jLabel4.setText("CHẤT LIỆU");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setMaximumSize(new java.awt.Dimension(37, 10));
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 10));
        panel5.add(jLabel4);

        jLabel12.setText("MÃ PHIẾU NHẬP");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 10));
        panel5.add(jLabel12);

        txt_maquat.setPreferredSize(new java.awt.Dimension(20, 20));
        panel5.add(txt_maquat);

        txt_chatlieu.setPreferredSize(new java.awt.Dimension(20, 20));
        panel5.add(txt_chatlieu);

        txt_maphieunhap.setPreferredSize(new java.awt.Dimension(20, 20));
        panel5.add(txt_maphieunhap);

        jLabel14.setText("TÊN QUẠT");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel14);

        jLabel2.setText("NGÀY SẢN XUẤT");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel2);

        jLabel8.setText("NHÂN VIÊN");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel8);

        txt_tenquat.setPreferredSize(new java.awt.Dimension(64, 20));
        panel5.add(txt_tenquat);
        panel5.add(txt_ngaysanxuat);
        panel5.add(txt_tennhanvien);

        jLabel10.setText("GIÁ NHẬP");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel10);

        jLabel5.setText("NHÀ SẢN XUẤT");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel5);

        jLabel11.setText("NHÀ CUNG CẤP");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel11);
        panel5.add(txt_gianhap);
        panel5.add(txt_nhasanxuat);

        panel5.add(combobox_nhacungcap);

        jLabel3.setText("SỐ LƯỢNG");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel3);
        panel5.add(jLabel19);

        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel5.add(jLabel15);
        panel5.add(txt_soluong);
        panel5.add(jLabel9);
        panel5.add(jLabel20);
        panel5.add(jLabel6);
        panel5.add(jLabel17);
        panel5.add(jLabel18);

        btn_addsanpham.setText("THÊM");
        panel5.add(btn_addsanpham);

        btn_editsanpham.setText("SỬA");
        panel5.add(btn_editsanpham);

        btn_deletesanpham.setText("XÓA");
        btn_deletesanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletesanphamActionPerformed(evt);
            }
        });
        panel5.add(btn_deletesanpham);

        panel3.add(panel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deletesanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletesanphamActionPerformed
        // TODO add your handling code here:
        
    int selectedRow = tablePhieuNhap.getSelectedRow();  


    if (selectedRow != -1) {
     
        modelPhieuNhap.removeRow(selectedRow);
    } else {
   
        
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa.");
    }
        
        
    }//GEN-LAST:event_btn_deletesanphamActionPerformed

    private void btn_nhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhaphangActionPerformed
        // TODO add your handling code here:
        
        
    String maPhieuNhap=txt_maphieunhap.getText();
    LocalDate ngaynhap = LocalDate.now(); 
    String tenncc = (String) combobox_nhacungcap.getSelectedItem();
    NhaCungCapBUS ncc=new NhaCungCapBUS();
    String maNCC= ncc.layMaNCCTheoTen(tenncc);
   
    String maNV = this.manv;
    QuatBUS quatbll=new QuatBUS();
    PhieuNhapBUS pnbll=new PhieuNhapBUS();
    ChiTietPhieuNhapBUS ctpnbll=new ChiTietPhieuNhapBUS();
    int tongTien = 0;
    DefaultTableModel model = modelPhieuNhap; 
    if (model.getRowCount() == 0) {
    JOptionPane.showMessageDialog(this, "Chưa thêm sản phẩm nhập!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    return;
}

    for (int i = 0; i < model.getRowCount(); i++) 
    {
    int gia = Integer.parseInt(model.getValueAt(i, 2).toString());
    int soLuong = Integer.parseInt(model.getValueAt(i, 3).toString());
    tongTien += gia * soLuong;
    }
    txt_tongtien.setText("TỔNG TIỀN :"+tongTien);
    PhieuNhapDTO pn = new PhieuNhapDTO(maPhieuNhap, ngaynhap, maNCC, maNV, tongTien);
    
     // In thông tin để debug
    System.out.println("Ma PN: " + maPhieuNhap);
    System.out.println("ngay nhap: " + ngaynhap);
    System.out.println("ten nCC: " + tenncc);
    System.out.println("ma ncc: " + maNCC);
    System.out.println("manv NV: " + maNV);
    System.out.println("Tổng tiền: " + tongTien);
    if (pnbll.themPhieuNhap(pn)) {
        System.out.println("Thêm thành công");
        
    } else {
       JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thất bại!");
       return;
    }

    
    
    
    
    System.out.println("\n\n\n\n");
     for (int i = 0; i < model.getRowCount(); i++) 
    {
    
    int gia = Integer.parseInt(model.getValueAt(i, 2).toString());
    int soLuong = Integer.parseInt(model.getValueAt(i, 3).toString());
    String maquat = model.getValueAt(i, 0).toString();
        System.out.println(""+maquat);

    ChiTietPhieuNhapDTO ctpn=new ChiTietPhieuNhapDTO(maPhieuNhap,maquat,soLuong,gia);
    ctpn.printDetails();
      try {
        boolean success = ctpnbll.themChiTietPhieuNhap(ctpn);
        if (!success) {
            System.out.println("Không thêm được chi tiết cho quạt mã: " + maquat);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        System.out.println("Lỗi khi thêm chi tiết phiếu nhập mã quạt: " + maquat);
    }
      
    if(quatbll.updatesoluongquat(maquat, soLuong)==true){
        JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thành công!");
        dispose();
    }
    

  

    }
 
    
      
        
    }//GEN-LAST:event_btn_nhaphangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String manv="test";
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemPhieuNhapDialog dialog = new ThemPhieuNhapDialog(new javax.swing.JFrame(), true,manv);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    
    public void locktext()
    {
        txt_maquat.setEditable(false);
        txt_tenquat.setEditable(false);
        txt_chatlieu.setEditable(false);
        txt_ngaysanxuat.setEditable(false);
        txt_maphieunhap.setEditable(false);
        txt_tennhanvien.setEditable(false);
        txt_nhasanxuat.setEditable(false);
        

    }
    


    private void createPhieuNhapTable() {
        String[] columnNames = {"Mã", "Tên", "Giá", "Số lượng", "Ngày sản xuất", "Chất liệu","Nhả Sản Xuất"};
        modelPhieuNhap = new DefaultTableModel(columnNames, 0); 
        tablePhieuNhap = new JTable(modelPhieuNhap);
        JScrollPane scrollPane = new JScrollPane(tablePhieuNhap);
        scrollPane.setPreferredSize(new Dimension(800, 150));

        panel_tablephieunhap.setLayout(new BorderLayout());
        panel_tablephieunhap.removeAll();
        panel_tablephieunhap.add(scrollPane, BorderLayout.SOUTH);
        panel_tablephieunhap.revalidate();
        panel_tablephieunhap.repaint();
    }
    
   

    
    private void addsanphamtoform() {
    btn_addsanpham.addActionListener(e -> {
        String ma = txt_maquat.getText();
        String ten = txt_tenquat.getText();
        String chatlieu = txt_chatlieu.getText();
        String ngaySX = txt_ngaysanxuat.getText();
        String NhaSanXuat=txt_nhasanxuat.getText();

       

        int gia = 0;
        int soLuong = 0;

        try {
            gia = Integer.parseInt(txt_gianhap.getText());
            soLuong = Integer.parseInt(txt_soluong.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Giá hoặc số lượng không hợp lệ");
            return;
        }

        modelPhieuNhap.addRow(new Object[]{ma, ten, gia, soLuong, ngaySX, chatlieu,NhaSanXuat});
    });
}

    
    
    private void loadComboBoxNhaCungCap() {
        NhaCungCapBUS nhaCungCapBLL = new NhaCungCapBUS();
        List<NhaCungCapDTO> danhSachNCC = nhaCungCapBLL.layTatCa();

        combobox_nhacungcap.removeAllItems(); // Xóa dữ liệu cũ

        for (NhaCungCapDTO ncc : danhSachNCC) {
            combobox_nhacungcap.addItem(ncc.getTenNCC()); // giả sử có phương thức getTenNhaCungCap()
        }
    }
    
    
    


    private void createSanPhamTable() {

        QuatBUS quatBLL = new QuatBUS();
        NhaSanXuatBUS nsxbus=new NhaSanXuatBUS();
        List<QuatDTO> danhSachQuat = quatBLL.layTatCa();

        String[] columnNames = {"Mã quạt", "Tên quạt", "Số lượng tồn"};
        Object[][] data = new Object[danhSachQuat.size()][3];

        for (int i = 0; i < danhSachQuat.size(); i++) {
            QuatDTO quat = danhSachQuat.get(i);
            data[i][0] = quat.getMaQuat();
            data[i][1] = quat.getTenQuat();
            data[i][2] = quat.getSoLuongTon();

        }

        modelsanpham = new DefaultTableModel(data, columnNames);
        tablesanpham = new JTable(modelsanpham);
        JScrollPane scrollPane = new JScrollPane(tablesanpham);

    
        tablesanpham.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tablesanpham.getSelectedRow();
                if (selectedRow >= 0) {
                    QuatDTO selectedQuat = danhSachQuat.get(selectedRow);
                    txt_maquat.setText(selectedQuat.getMaQuat());
                    txt_tenquat.setText(selectedQuat.getTenQuat());
                    txt_chatlieu.setText(selectedQuat.getChatLieu());
                    txt_ngaysanxuat.setText(selectedQuat.getNgaySanXuat());
                    String tennhasanxuat=nsxbus.getTenNXSByMaNSX(selectedQuat.getMaNSX());
                    System.out.println(tennhasanxuat);
                    txt_nhasanxuat.setText(tennhasanxuat);

                }
            }
        });

        panel.setLayout(new java.awt.BorderLayout());
        panel.removeAll();
        panel.add(scrollPane, java.awt.BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
        
        
        
        PhieuNhapBUS pnbll=new PhieuNhapBUS();
        txt_maphieunhap.setText(pnbll.taoMaPhieuNhapTuDong());
         NhanVienBUS nvbus=new NhanVienBUS();
        String tennv=nvbus.getNameNVByMaNV(this.manv);
        txt_tennhanvien.setText(tennv);


    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addsanpham;
    private javax.swing.JButton btn_deletesanpham;
    private javax.swing.JButton btn_editsanpham;
    private javax.swing.JButton btn_nhaphang;
    private javax.swing.JComboBox<String> combobox_nhacungcap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel5;
    private java.awt.Panel panel_tablephieunhap;
    private java.awt.Panel panel_tablesanpham;
    private java.awt.Panel panel_tittle;
    private javax.swing.JTextField txt_chatlieu;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_maphieunhap;
    private javax.swing.JTextField txt_maquat;
    private javax.swing.JTextField txt_ngaysanxuat;
    private javax.swing.JTextField txt_nhasanxuat;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tennhanvien;
    private javax.swing.JTextField txt_tenquat;
    private javax.swing.JLabel txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
