/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Dialog;

/**
 *
 * @author nguye
 */
public class ThemQuatDia extends javax.swing.JFrame {

    /**
     * Creates new form ThemQuatDia
     */
    public ThemQuatDia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        jButton3 = new javax.swing.JButton();
        panel8 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setMinimumSize(new java.awt.Dimension(118, 100));
        panel1.setPreferredSize(new java.awt.Dimension(1024, 100));
        panel1.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("THÊM QUẠT");
        panel1.add(jLabel10, new java.awt.GridBagConstraints());

        getContentPane().add(panel1, java.awt.BorderLayout.PAGE_START);

        panel2.setPreferredSize(new java.awt.Dimension(1024, 150));
        panel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("THÊM");
        panel5.add(jButton1);

        jButton2.setText("HỦY");
        panel5.add(jButton2);

        panel2.add(panel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel2, java.awt.BorderLayout.PAGE_END);

        panel3.setPreferredSize(new java.awt.Dimension(300, 200));
        panel3.setLayout(new java.awt.BorderLayout());

        panel7.setPreferredSize(new java.awt.Dimension(300, 50));
        panel7.setLayout(new java.awt.GridBagLayout());

        jButton3.setText("HÌNH MINH HỌA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 108, 6, 117);
        panel7.add(jButton3, gridBagConstraints);

        panel3.add(panel7, java.awt.BorderLayout.NORTH);

        panel8.setPreferredSize(new java.awt.Dimension(300, 400));

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        panel3.add(panel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel3, java.awt.BorderLayout.LINE_START);

        panel4.setMinimumSize(new java.awt.Dimension(470, 100));
        panel4.setPreferredSize(new java.awt.Dimension(919, 400));
        panel4.setLayout(new java.awt.GridLayout(6, 1, 100, 0));

        jLabel2.setText("MÃ QUẠT");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel2);

        jLabel9.setText("TÊN QUẠT");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel9);

        jLabel7.setText("GIÁ");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel7);

        jTextField2.setPreferredSize(new java.awt.Dimension(64, 10));
        panel4.add(jTextField2);

        jTextField1.setPreferredSize(new java.awt.Dimension(64, 10));
        panel4.add(jTextField1);

        jTextField5.setPreferredSize(new java.awt.Dimension(64, 10));
        panel4.add(jTextField5);

        jLabel5.setText("SỐ LƯỢNG TỒN");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel5);

        jLabel6.setText("NHÀ SẢN XUẤT");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel6);

        jLabel4.setText("NGÀY SẢN XUẤT");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel4);
        panel4.add(jTextField4);
        panel4.add(jTextField3);
        panel4.add(jTextField6);

        jLabel8.setText("CHẤT LIỆU");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel8);

        jLabel3.setText("LOẠI SẢN PHẨM");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel4.add(jLabel3);
        panel4.add(jLabel1);
        panel4.add(jTextField7);
        panel4.add(jTextField8);

        getContentPane().add(panel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemQuatDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemQuatDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemQuatDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemQuatDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemQuatDia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    // End of variables declaration//GEN-END:variables
}
