/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.*;
import BUS.QuatBUS;
import java.util.List;
import DTO.QuatDTO;
import BUS.NhaCungCapBUS;
import DTO.NhaCungCapDTO;
import BUS.PhieuNhapBUS;



/**
 *
 * @author nguye
 */
public class ThemPhieuNhapDialog extends javax.swing.JDialog {
    private DefaultTableModel modelPhieuNhap;  // Lưu model để thêm dòng sau này
    private JTable tablePhieuNhap;
    

    /**
     * Creates new form ThemPhieuNhapDialog
     */
    public ThemPhieuNhapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         createSanPhamTable();
         createPhieuNhapTable();
         loadComboBoxNhaCungCap();
         addsanphamtoform();
         loadmapnandnhanvien();
        

         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        btn_nhaphang = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        txt_maphieunhap = new javax.swing.JTextField();
        txt_tennhanvien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panel_tablesanpham = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        panel_7 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        panel_forms = new javax.swing.JPanel();
        panel_formsanpham = new javax.swing.JPanel();
        panel_tablephieunhap = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        btn_addsanpham = new java.awt.Button();
        btn_suasanpham = new java.awt.Button();
        txt_maquat = new javax.swing.JTextField();
        txt_tenquat = new javax.swing.JTextField();
        txt_gianhap = new javax.swing.JTextField();
        txt_chatlieu = new javax.swing.JTextField();
        txt_ngaysanxuat = new javax.swing.JTextField();
        combobox_nhacungcap = new javax.swing.JComboBox<>();
        txt_soluong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_nhaphang.setLabel("NHẬP HÀNG");

        jLabel2.setText("MÃ PHIẾU NHẬP");

        txt_maphieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maphieunhapActionPerformed(evt);
            }
        });

        jLabel3.setText("NHÂN VIÊN ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_tennhanvien)
            .addComponent(txt_maphieunhap)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btn_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_maphieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(btn_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        panel_tablesanpham.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout panel_tablesanphamLayout = new javax.swing.GroupLayout(panel_tablesanpham);
        panel_tablesanpham.setLayout(panel_tablesanphamLayout);
        panel_tablesanphamLayout.setHorizontalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panel_tablesanphamLayout.setVerticalGroup(
            panel_tablesanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        getContentPane().add(panel_tablesanpham, java.awt.BorderLayout.LINE_START);

        textField1.setText("NHẬP DỮ LIỆU ĐỂ TÌM KIẾM");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_START);

        panel_7.setMaximumSize(new java.awt.Dimension(100, 100));
        panel_7.setMinimumSize(new java.awt.Dimension(50, 50));
        panel_7.setLayout(new javax.swing.BoxLayout(panel_7, javax.swing.BoxLayout.LINE_AXIS));

        panel.setLayout(new java.awt.BorderLayout());
        panel_7.add(panel);

        getContentPane().add(panel_7, java.awt.BorderLayout.PAGE_END);

        panel_forms.setLayout(new java.awt.BorderLayout());

        panel_formsanpham.setLayout(new java.awt.BorderLayout());
        panel_forms.add(panel_formsanpham, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panel_tablephieunhapLayout = new javax.swing.GroupLayout(panel_tablephieunhap);
        panel_tablephieunhap.setLayout(panel_tablephieunhapLayout);
        panel_tablephieunhapLayout.setHorizontalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        panel_tablephieunhapLayout.setVerticalGroup(
            panel_tablephieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_forms.add(panel_tablephieunhap, java.awt.BorderLayout.PAGE_END);

        label1.setText("MÃ SẢN PHẨM");

        label2.setText("TÊN SẢN PHẨM");

        label3.setText(" GIÁ NHẬP ");

        label4.setText("CHẤT LIỆU");

        label5.setText("NGÀY SẢN XUẤT");

        label6.setText("NHÀ CUNG CẤP");

        btn_addsanpham.setLabel("THÊM SẢN PHẢM");

        btn_suasanpham.setLabel("SỬA SẢN PHẢM");

        txt_maquat.setMinimumSize(new java.awt.Dimension(150, 30));

        txt_tenquat.setMinimumSize(new java.awt.Dimension(150, 30));

        txt_gianhap.setMinimumSize(new java.awt.Dimension(150, 30));
        txt_gianhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gianhapActionPerformed(evt);
            }
        });

        txt_chatlieu.setText("jTextField1");
        txt_chatlieu.setMinimumSize(new java.awt.Dimension(150, 30));

        txt_ngaysanxuat.setText("jTextField2");

        jLabel1.setText("SỐ LƯỢNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_maquat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_tenquat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txt_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soluong)
                            .addComponent(btn_addsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_chatlieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaysanxuat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_nhacungcap, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                            .addComponent(btn_suasanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maquat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_chatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenquat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaysanxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_nhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        panel_forms.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_forms, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void txt_gianhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gianhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gianhapActionPerformed

    private void txt_maphieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maphieunhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maphieunhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuNhapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemPhieuNhapDialog dialog = new ThemPhieuNhapDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            
        });
    }

    public void loadmapnandnhanvien()
    {
        String mapn= PhieuNhapBUS.taoMaPhieuNhapTuDong();
        txt_maphieunhap.setText(mapn) ;
    }
    
    private void addsanphamtoform() {
    btn_addsanpham.addActionListener(e -> {
        String ma = txt_maquat.getText();
        String ten = txt_tenquat.getText();
        String chatlieu = txt_chatlieu.getText();
        String ngaySX = txt_ngaysanxuat.getText();
        String nhacungcap=(String) combobox_nhacungcap.getSelectedItem();
       

        int gia = 0;
        int soLuong = 0;

        try {
            gia = Integer.parseInt(txt_gianhap.getText());
            soLuong = Integer.parseInt(txt_soluong.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Giá hoặc số lượng không hợp lệ");
            return;
        }

        modelPhieuNhap.addRow(new Object[]{ma, ten, gia, soLuong, ngaySX, chatlieu,nhacungcap});
    });
}

    
    
    
    private void loadComboBoxNhaCungCap() {
    NhaCungCapBUS nhaCungCapBLL = new NhaCungCapBUS();
    List<NhaCungCapDTO> danhSachNCC = nhaCungCapBLL.layTatCa();

    combobox_nhacungcap.removeAllItems(); // Xóa dữ liệu cũ

    for (NhaCungCapDTO ncc : danhSachNCC) {
        combobox_nhacungcap.addItem(ncc.getTenNCC()); // giả sử có phương thức getTenNhaCungCap()
    }
}

    
    
    
    
private void createSanPhamTable() {
    QuatBUS quatBLL = new QuatBUS();
    List<QuatDTO> danhSachQuat = quatBLL.layTatCa();

    String[] columnNames = {"Mã quạt", "Tên quạt", "Số lượng tồn"};
    Object[][] data = new Object[danhSachQuat.size()][3];

    for (int i = 0; i < danhSachQuat.size(); i++) {
        QuatDTO quat = danhSachQuat.get(i);
        data[i][0] = quat.getMaQuat();
        data[i][1] = quat.getTenQuat();
        data[i][2] = quat.getSoLuongTon();
    }

    DefaultTableModel model = new DefaultTableModel(data, columnNames);
    JTable table = new JTable(model);
    JScrollPane scrollPane = new JScrollPane(table);

    // Thêm sự kiện chọn dòng
    table.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int selectedRow = table.getSelectedRow();
            if (selectedRow >= 0) {
                QuatDTO selectedQuat = danhSachQuat.get(selectedRow);
                txt_maquat.setText(selectedQuat.getMaQuat());
                txt_tenquat.setText(selectedQuat.getTenQuat());
              txt_chatlieu.setText(selectedQuat.getChatLieu());
               txt_ngaysanxuat.setText(selectedQuat.getNgaySanXuat());
                
                // Các field khác nếu có...
            }
        }
    });

    panel_tablesanpham.setLayout(new java.awt.BorderLayout());
    panel_tablesanpham.removeAll();
    panel_tablesanpham.add(scrollPane, java.awt.BorderLayout.CENTER);
    panel_tablesanpham.revalidate();
    panel_tablesanpham.repaint();
}

  




  
private void createPhieuNhapTable() {
    String[] columnNames = {"Mã", "Tên", "Giá", "Số lượng", "Ngày sản xuất", "Chất liệu", "Nhà cung cấp"};
    modelPhieuNhap = new DefaultTableModel(columnNames, 0); // Tạo model rỗng
    tablePhieuNhap = new JTable(modelPhieuNhap);
    JScrollPane scrollPane = new JScrollPane(tablePhieuNhap);
    scrollPane.setPreferredSize(new Dimension(800, 150));

    panel.setLayout(new BorderLayout());
    panel.removeAll();
    panel.add(scrollPane, BorderLayout.SOUTH);
    panel.revalidate();
    panel.repaint();
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_addsanpham;
    private java.awt.Button btn_nhaphang;
    private java.awt.Button btn_suasanpham;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> combobox_nhacungcap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_7;
    private javax.swing.JPanel panel_forms;
    private javax.swing.JPanel panel_formsanpham;
    private javax.swing.JPanel panel_tablephieunhap;
    private javax.swing.JPanel panel_tablesanpham;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txt_chatlieu;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_maphieunhap;
    private javax.swing.JTextField txt_maquat;
    private javax.swing.JTextField txt_ngaysanxuat;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tennhanvien;
    private javax.swing.JTextField txt_tenquat;
    // End of variables declaration//GEN-END:variables
}
